# Data Wrangling

This file merges 6 csv data sets to be exported as one file to Tableau.

### I. Import libraries

In [1]:
import pandas as pd

### II. Import csv files

Import all files

In [2]:
reviews_1 = pd.read_csv("raw_data/reviews_1.csv", encoding = 'latin1')
reviews_2 = pd.read_csv("raw_data/reviews_2.csv", encoding = 'latin1')
reviews_3 = pd.read_csv("raw_data/reviews_3.csv", encoding = 'latin1')
reviews_4 = pd.read_csv("raw_data/reviews_4.csv", encoding = 'latin1')
reviews_5 = pd.read_csv("raw_data/reviews_5.csv", encoding = 'latin1')
reviews_6 = pd.read_csv("raw_data/reviews_6.csv", encoding = 'latin1')

reviews_6.head()

,phone_url,date,lang,country,source,domain,score,score_max,extract,author,product
0,/cellphones/samsung-instinct-sph-m800/,9/16/2011,en,us,Phone Arena,phonearena.com,8.0,10.0,I've had the phone for awhile and it's a prett...,ajabrams95,Samsung Instinct HD
1,/cellphones/samsung-instinct-sph-m800/,2/13/2014,en,us,Amazon,amazon.com,6.0,10.0,to be clear it is not the sellers fault that t...,Stephanie,Samsung SPH M800 Instinct
2,/cellphones/samsung-instinct-sph-m800/,12/30/2011,en,us,Phone Scoop,phonescoop.com,9.0,10.0,Well i love this phone. i have had ton of phon...,snickers,Instinct M800
3,/cellphones/samsung-instinct-sph-m800/,10/18/2008,en,us,HandCellPhone,handcellphone.com,4.0,10.0,I have had my Instinct for several months now ...,A4C,Samsung Instinct
4,/cellphones/samsung-instinct-sph-m800/,9/6/2008,en,us,Reviewed.com,reviewed.com,6.0,10.0,i have had this instinct phone for about two m...,betaBgood,Samsung Instinct

Check column names

In [3]:
reviews_6.columns

Index(['phone_url', 'date', 'lang', 'country', 'source', 'domain', 'score',
       'score_max', 'extract', 'author', 'product'],
      dtype='object')

Concatenate csv files

In [4]:
reviews = pd.concat([reviews_1, reviews_2, reviews_3, reviews_4, reviews_5, reviews_6], ignore_index=True)
reviews.head()

,phone_url,date,lang,country,source,domain,score,score_max,extract,author,product
0,/cellphones/samsung-galaxy-s8/,5/2/2017,en,us,Verizon Wireless,verizonwireless.com,10.0,10.0,As a diehard Samsung fan who has had every Sam...,CarolAnn35,Samsung Galaxy S8
1,/cellphones/samsung-galaxy-s8/,4/28/2017,en,us,Phone Arena,phonearena.com,10.0,10.0,Love the phone. the phone is sleek and smooth ...,james0923,Samsung Galaxy S8
2,/cellphones/samsung-galaxy-s8/,5/4/2017,en,us,Amazon,amazon.com,6.0,10.0,Adequate feel. Nice heft. Processor's still sl...,R. Craig,"Samsung Galaxy S8 (64GB) G950U 5.8"" 4G LTE Unl..."
3,/cellphones/samsung-galaxy-s8/,5/2/2017,en,us,Samsung,samsung.com,9.2,10.0,Never disappointed. One of the reasons I've be...,Buster2020,Samsung Galaxy S8 64GB (AT&T)
4,/cellphones/samsung-galaxy-s8/,5/11/2017,en,us,Verizon Wireless,verizonwireless.com,4.0,10.0,I've now found that i'm in a group of people t...,S Ate Mine,Samsung Galaxy S8

### III. Clean data

In [5]:
reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1415133 entries, 0 to 1415132
Data columns (total 11 columns):
 #   Column     Non-Null Count    Dtype
---  ------     --------------    -----
 0   phone_url  1415133 non-null  object
 1   date       1415133 non-null  object
 2   lang       1415133 non-null  object
 3   country    1415133 non-null  object
 4   source     1415133 non-null  object
 5   domain     1415133 non-null  object
 6   score      1351644 non-null  float64
 7   score_max  1351644 non-null  float64
 8   extract    1395772 non-null  object
 9   author     1351931 non-null  object
 10  product    1415132 non-null  object
dtypes: float64(2), object(9)
memory usage: 118.8+ MB

Identify null values

In [6]:
missing_values = reviews.isna().sum().sort_values(ascending = False)
missing_values

score_max    63489
score        63489
author       63202
extract      19361
product          1
domain           0
source           0
country          0
lang             0
date             0
phone_url        0
dtype: int64

Get the percentage of null values per column

In [7]:
missing_values.loc[missing_values.gt(0)]/len(reviews)

score_max    4.486433e-02
score        4.486433e-02
author       4.466153e-02
extract      1.368140e-02
product      7.066474e-07
dtype: float64

Since missing values are only 4 percent, the rows are dropped

In [8]:
reviews.dropna(inplace = True)

In [9]:
missing_values

score_max    63489
score        63489
author       63202
extract      19361
product          1
domain           0
source           0
country          0
lang             0
date             0
phone_url        0
dtype: int64

Since column 'score_max' contains only the same value, and columns 'domain' and 'extract' are irrelevant for a quantitative analysis, they are also dropped.

In [10]:
reviews.drop(['score_max', 'domain', 'extract'], axis = 'columns', inplace = True)
reviews.head()

,phone_url,date,lang,country,source,score,author,product
0,/cellphones/samsung-galaxy-s8/,5/2/2017,en,us,Verizon Wireless,10.0,CarolAnn35,Samsung Galaxy S8
1,/cellphones/samsung-galaxy-s8/,4/28/2017,en,us,Phone Arena,10.0,james0923,Samsung Galaxy S8
2,/cellphones/samsung-galaxy-s8/,5/4/2017,en,us,Amazon,6.0,R. Craig,"Samsung Galaxy S8 (64GB) G950U 5.8"" 4G LTE Unl..."
3,/cellphones/samsung-galaxy-s8/,5/2/2017,en,us,Samsung,9.2,Buster2020,Samsung Galaxy S8 64GB (AT&T)
4,/cellphones/samsung-galaxy-s8/,5/11/2017,en,us,Verizon Wireless,4.0,S Ate Mine,Samsung Galaxy S8

Since the entries in column 'product' appear in varying forms, they are replaced by an extraction from the url.

In [12]:
reviews['product'] = (reviews['phone_url'].str.split('/')
                                          .str.get(2))
reviews.head()

,phone_url,date,lang,country,source,score,author,product
0,/cellphones/samsung-galaxy-s8/,5/2/2017,en,us,Verizon Wireless,10.0,CarolAnn35,samsung-galaxy-s8
1,/cellphones/samsung-galaxy-s8/,4/28/2017,en,us,Phone Arena,10.0,james0923,samsung-galaxy-s8
2,/cellphones/samsung-galaxy-s8/,5/4/2017,en,us,Amazon,6.0,R. Craig,samsung-galaxy-s8
3,/cellphones/samsung-galaxy-s8/,5/2/2017,en,us,Samsung,9.2,Buster2020,samsung-galaxy-s8
4,/cellphones/samsung-galaxy-s8/,5/11/2017,en,us,Verizon Wireless,4.0,S Ate Mine,samsung-galaxy-s8

In [13]:
reviews['product'].value_counts()

samsung-galaxy-s6         15869
samsung-galaxy-s7-edge    15568
apple-iphone-5s           15543
samsung-galaxy-s5         15282
motorola-moto-g           14431
                          ...
sanyo-s750                    1
philips-xenium-9-9s           1
blu-life-one                  1
tiptel-ergophone-6010         1
toshiba-k01                   1
Name: product, Length: 5508, dtype: int64

Check product grouped for initial analysis

In [14]:
product_grouped = reviews.groupby('product')
product_grouped.first().reset_index()

,product,phone_url,date,lang,country,source,score,author
0,acer-acer-liquid-m220,/cellphones/acer-acer-liquid-m220/,29/6/2015,en,us,Amazon,2.0,karitoki411
1,acer-allegro,/cellphones/acer-allegro/,9/8/2012,it,it,Ciao,8.0,babetti
2,acer-betouch-e100,/cellphones/acer-betouch-e100/,12/26/2014,en,gb,Amazon,2.0,marilyn mertens
3,acer-betouch-e101,/cellphones/acer-betouch-e101/,1/2/2010,en,gb,Amazon,2.0,A.Humphreys
4,acer-betouch-e110,/cellphones/acer-betouch-e110/,4/24/2011,en,gb,Amazon,6.0,"C. L. Weekes ""Charliegadgets"""
...,...,...,...,...,...,...,...,...
5503,zte-zmax,/cellphones/zte-zmax/,5/10/2016,en,us,CNET,10.0,youngkim3000
5504,zte-zmax-2,/cellphones/zte-zmax-2/,11/22/2016,en,us,Newegg,8.0,Chuck C.
5505,zte-zte-g-r221,/cellphones/zte-zte-g-r221/,1/8/2017,ru,ru,Irecommend,10.0,LALYA30
5506,zte-zte-g-s213,/cellphones/zte-zte-g-s213/,1/19/2013,en,us,Phone Arena,7.0,Crisma
5507,zte-zte-u-f930,/cellphones/zte-zte-u-f930/,10/23/2012,it,it,Ciao,6.0,keting11

For deeper analysis column 'brand' is added.

In [15]:
reviews['brand'] = (reviews['product'].str.split("-")
                                      .str.get(0))
                                      
reviews.head()

,phone_url,date,lang,country,source,score,author,product,brand
0,/cellphones/samsung-galaxy-s8/,5/2/2017,en,us,Verizon Wireless,10.0,CarolAnn35,samsung-galaxy-s8,samsung
1,/cellphones/samsung-galaxy-s8/,4/28/2017,en,us,Phone Arena,10.0,james0923,samsung-galaxy-s8,samsung
2,/cellphones/samsung-galaxy-s8/,5/4/2017,en,us,Amazon,6.0,R. Craig,samsung-galaxy-s8,samsung
3,/cellphones/samsung-galaxy-s8/,5/2/2017,en,us,Samsung,9.2,Buster2020,samsung-galaxy-s8,samsung
4,/cellphones/samsung-galaxy-s8/,5/11/2017,en,us,Verizon Wireless,4.0,S Ate Mine,samsung-galaxy-s8,samsung

Check brand grouped for initial analysis

In [16]:
brand_grouped = reviews.groupby('brand')
brand_grouped.first().reset_index()

,brand,phone_url,date,lang,country,source,score,author,product
0,acer,/cellphones/acer-liquid-z630/,8/19/2016,en,gb,Ciao,6.0,cynthia-melky,acer-liquid-z630
1,alcatel,/cellphones/alcatel-one-touch-idol-4s/,9/26/2016,en,us,CNET,10.0,JoeRanger,alcatel-one-touch-idol-4s
2,amazon,/cellphones/amazon-fire-phone/,2/28/2016,en,us,CNET,6.0,KungalooshMeganium,amazon-fire-phone
3,amoi,/cellphones/amoi-a203/,7/1/2012,fr,fr,LesMobiles,9.6,peter13,amoi-a203
4,amplicom,/cellphones/amplicom-m5010/,1/11/2016,de,de,Amazon,10.0,Gottfried Fiala,amplicom-m5010
...,...,...,...,...,...,...,...,...,...
160,yezz,/cellphones/yezz-billy-4-7/,10/20/2014,en,us,Amazon,10.0,Louis A Cruz,yezz-billy-4-7
161,yota,/cellphones/yota-yotaphone-2/,12/12/2014,en,us,CNET,9.0,Vladimir.V.Kozlov,yota-yotaphone-2
162,yu,/cellphones/yu-yuphoria/,5/17/2017,en,in,Smartprix,9.0,barath uppalancha,yu-yuphoria
163,zopo,/cellphones/zopo-color-c-zp330/,11/21/2015,en,gb,Amazon,2.0,Simon King,zopo-color-c-zp330
164,zte,/cellphones/zte-axon-7/,12/22/2016,en,us,CNET,10.0,mountain_man_ky,zte-axon-7

Since it is irrelevant for further analysis, drop column "phone_url"

In [17]:
reviews.drop(['phone_url'], axis = 'columns', inplace = True)

In [18]:
reviews.head()

,date,lang,country,source,score,author,product,brand
0,5/2/2017,en,us,Verizon Wireless,10.0,CarolAnn35,samsung-galaxy-s8,samsung
1,4/28/2017,en,us,Phone Arena,10.0,james0923,samsung-galaxy-s8,samsung
2,5/4/2017,en,us,Amazon,6.0,R. Craig,samsung-galaxy-s8,samsung
3,5/2/2017,en,us,Samsung,9.2,Buster2020,samsung-galaxy-s8,samsung
4,5/11/2017,en,us,Verizon Wireless,4.0,S Ate Mine,samsung-galaxy-s8,samsung

In [19]:
reviews.shape

(1275917, 8)

In [27]:
reviews['country'].nunique()

40

In [21]:
reviews['date'].str.split('/').str.get(2).max()

'2017'

In [22]:
reviews['date'].str.split('/').str.get(2).min()

'1970'

## IV. Export dataframe to csv file

In [23]:
reviews.to_csv("cell_phones.csv")